# --- Stage 1: Build Angular Frontend ---
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

# --- Stage 2: Serve Using NGINX ---
FROM nginx:alpine

# Copy compiled Angular files to NGINX html folder
COPY --from=build /app/dist/angular-15-crud /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
